/**
 * ============================================================
 * config.service.ts
 * ============================================================
 *
 * Exposes runtime configuration injected by env.js at deploy time.
 * The nginx Docker entrypoint writes env.js from container environment
 * variables, so OAuth settings can differ per deployment without
 * rebuilding the Angular app.
 *
 * Exported:
 *   AppConfigService — root-level injectable
 *
 * Getters:
 *   googleClientId  — string: Google OAuth client id (empty if unset)
 *   appleClientId   — string: Apple OAuth client id (empty if unset)
 *   googleEnabled   — boolean: true when Google login is available for this origin
 *   appleEnabled    — boolean: true when Apple login is available for this origin
 * ============================================================
 */
import { Injectable } from '@angular/core';

// Typed interface for the runtime window config set by env.js (generated by
// the nginx Docker entrypoint from container environment variables).
interface WindowEnv {
  GOOGLE_CLIENT_ID?: string;
  APPLE_CLIENT_ID?: string;
  GOOGLE_ALLOWED_ORIGINS?: string;
  APPLE_ALLOWED_ORIGINS?: string;
}

declare global {
  interface Window {
    __env__?: WindowEnv;
  }
}

@Injectable({ providedIn: 'root' })
// AppConfigService exposes runtime configuration injected by env.js at deploy time.
export class AppConfigService {
  private readonly env: WindowEnv = window.__env__ ?? {};

  get googleClientId(): string {
    return this.env.GOOGLE_CLIENT_ID ?? '';
  }

  get appleClientId(): string {
    return this.env.APPLE_CLIENT_ID ?? '';
  }

  get googleEnabled(): boolean {
    if (!this.googleClientId) {
      return false;
    }

    return this.isProviderEnabledForOrigin(this.env.GOOGLE_ALLOWED_ORIGINS);
  }

  get appleEnabled(): boolean {
    if (!this.appleClientId) {
      return false;
    }

    return this.isProviderEnabledForOrigin(this.env.APPLE_ALLOWED_ORIGINS);
  }

    // OAuth buttons are suppressed unless the current origin is explicitly allowed.
  private isProviderEnabledForOrigin(rawAllowedOrigins: string | undefined): boolean {
    const currentOrigin = window.location.origin;
    const isLocalhost =
      currentOrigin.includes('://localhost') ||
      currentOrigin.includes('://127.0.0.1');

    const allowed = (rawAllowedOrigins ?? '')
      .split(',')
      .map((origin) => origin.trim())
      .filter((origin) => origin.length > 0);

    // Safer default in local/dev: hide OAuth buttons unless explicitly allowlisted.
    if (allowed.length === 0) {
      return !isLocalhost;
    }

    return allowed.includes('*') || allowed.includes(currentOrigin);
  }
}
