import { Injectable } from '@angular/core';

// Typed interface for the runtime window config set by env.js (generated by
// the nginx Docker entrypoint from container environment variables).
interface WindowEnv {
  GOOGLE_CLIENT_ID?: string;
  APPLE_CLIENT_ID?: string;
}

declare global {
  interface Window {
    __env__?: WindowEnv;
  }
}

@Injectable({ providedIn: 'root' })
export class AppConfigService {
  private readonly env: WindowEnv = window.__env__ ?? {};

  get googleClientId(): string {
    return this.env.GOOGLE_CLIENT_ID ?? '';
  }

  get appleClientId(): string {
    return this.env.APPLE_CLIENT_ID ?? '';
  }

  get googleEnabled(): boolean {
    return !!this.googleClientId;
  }

  get appleEnabled(): boolean {
    return !!this.appleClientId;
  }
}
